### ISSUE TITLE
Compilation fails due to "invalid frame state"

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1050]
This is a new error that we are getting regularly on RC13:

```
Thread[JVMCI CompilerThread1,9,system]: Compilation of de.hpi.swa.graal.squeak.nodes.primitives.impl.ControlPrimitivesFactory$PrimSignalNodeFactory$PrimSignalNodeGen.executeWithArguments(VirtualFrame, Object[]) failed:
org.graalvm.compiler.graph.GraalGraphError: Invalid frame state 17|FrameState@-4[AFTER_EXCEPTION_BCI]
	at node: 655|ForeignCall#new_instance_or_null(KlassPointer)Object
	at org.graalvm.compiler.hotspot.HotSpotDebugInfoBuilder.raiseInvalidFrameStateError(HotSpotDebugInfoBuilder.java:122)
	at org.graalvm.compiler.hotspot.HotSpotDebugInfoBuilder.computeFrameForState(HotSpotDebugInfoBuilder.java:92)
	at org.graalvm.compiler.core.gen.DebugInfoBuilder.build(DebugInfoBuilder.java:101)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.stateForWithExceptionEdge(NodeLIRBuilder.java:748)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.stateFor(NodeLIRBuilder.java:740)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.state(NodeLIRBuilder.java:729)
	at org.graalvm.compiler.nodes.extended.ForeignCallNode.generate(ForeignCallNode.java:171)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.emitNode(NodeLIRBuilder.java:473)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doRoot(NodeLIRBuilder.java:464)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doBlock(NodeLIRBuilder.java:379)
	at org.graalvm.compiler.core.LIRGenerationPhase.emitBlock(LIRGenerationPhase.java:81)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:71)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:46)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:117)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:109)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR0(LIRCompilerBackend.java:150)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR(LIRCompilerBackend.java:113)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:83)
	at org.graalvm.compiler.core.target.Backend.emitBackEnd(Backend.java:280)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:185)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:198)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:182)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:99)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:172)
	at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:331)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:138)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:105)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:708)
```

Here's the corresponding Graal dump: [graal_diagnostics_28231.zip](https://github.com/oracle/graal/files/2948433/graal_diagnostics_28231.zip). Any idea how this can be fixed?

**Comment by thomaswue** [comment]
Thanks for the report. Can you confirm that this does not happen with RC12? Can we reproduce this on our machines?

**Comment by fniephaus** [comment]
It's the first time we are seeing this error and we only just upgraded from RC12 to RC13. Our code base is not public yet, but I'm happy to provide everything needed to reproduce this in an email if you like.

**Comment by gilles-duboscq** [comment]
This should be fixed by b59108dee720ab4a051aa734ccaa322c09e117d5 (not in rc14 but in the next one).

**Comment by fniephaus** [comment]
Perfect, thanks a lot! Will build a VM from tip to confirm this is fixed and will re-open this issue if the problem persists.

**Comment by fniephaus** [comment]
I'm afraid the problem is still there:
```
Thread[JVMCI CompilerThread2,9,system]: Compilation of de.hpi.swa.graal.squeak.nodes.primitives.impl.ControlPrimitivesFactory$PrimSignalNodeFactory$PrimSignalNodeGen.executeWithArguments(VirtualFrame, Object[]) failed:
org.graalvm.compiler.graph.GraalGraphError: Invalid frame state 18|FrameState@-4[AFTER_EXCEPTION_BCI]
	at node: 538|ForeignCall#new_instance_or_null(KlassPointer)Object
	at org.graalvm.compiler.hotspot.HotSpotDebugInfoBuilder.raiseInvalidFrameStateError(HotSpotDebugInfoBuilder.java:122)
	at org.graalvm.compiler.hotspot.HotSpotDebugInfoBuilder.computeFrameForState(HotSpotDebugInfoBuilder.java:92)
	at org.graalvm.compiler.core.gen.DebugInfoBuilder.build(DebugInfoBuilder.java:101)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.stateForWithExceptionEdge(NodeLIRBuilder.java:748)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.stateFor(NodeLIRBuilder.java:740)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.state(NodeLIRBuilder.java:729)
	at org.graalvm.compiler.nodes.extended.ForeignCallNode.generate(ForeignCallNode.java:171)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.emitNode(NodeLIRBuilder.java:473)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doRoot(NodeLIRBuilder.java:464)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doBlock(NodeLIRBuilder.java:379)
	at org.graalvm.compiler.core.LIRGenerationPhase.emitBlock(LIRGenerationPhase.java:81)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:71)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:46)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:117)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:109)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR0(LIRCompilerBackend.java:150)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR(LIRCompilerBackend.java:113)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:83)
	at org.graalvm.compiler.core.target.Backend.emitBackEnd(Backend.java:280)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:185)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:198)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:189)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:97)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:177)
	at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:337)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:138)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:105)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:708)
```

Corresponding dump: [graal_diagnostics_66210.zip](https://github.com/oracle/graal/files/2983655/graal_diagnostics_66210.zip).

I have a) verified I'm still seeing the error on RC14, b) build a new VM via `mx --dynamicimports /substratevm,/tools build` in `vm/` from `master` @ 86d3a1c69f80c5b28e97fb9f2fb40325f35a6326 (which includes https://github.com/oracle/graal/commit/b59108dee720ab4a051aa734ccaa322c09e117d5), and c) reproduced the problem with the custom-built VM.

**Comment by fniephaus** [comment]
Unfortunately, I can't seem to re-open the issue...

**Comment by gilles-duboscq** [comment]
Hey @fniephaus, any way you could share something we can use to reproduce? I created a test case that reproduces the same graph shape and I got the same failure earlier but it's fixed for my test case now. I can't see anything different in the new graph you sent.
If you can not share publicly, please use the email on my github profile.

**Comment by DipanjanGoswami** [comment]
Hi. I was looking into this issue and trying to find some solution. May I know any details regarding this issue.

**Comment by fniephaus** [comment]
I can no longer reproduce this.
