### ISSUE TITLE
[native-image]Is it possible to disable eager class initialization at compile time?

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#1183]
We have managed to compile a shared native image of Apache RocketMQ client with one API exposed as a trial. However, we find previous experiences are less useful when trying to expose more APIs because of eager class initialization mechanism.  Different execution path is reached when a new API is called, reporting new exceptions or errors. We know they are caused by the class initializations are not rerun or delayed at run time, but we don't know which classes are they. It's not easy to locate the class with exception message.
Is it possible to disable eager class initialization at compile time and delay all class initialization to run time by default, and only specify the safe class initialization at compile time manually? It would be easier to implement SVM in this way.

**Comment by ziyilin** [comment]
I have modified the substrate a little to use an option to use ConservativeClassInitialization which seems can delay class initialization to runtime. 
```
diff --git a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/HostedConfiguration.java b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/HostedConfiguration.java
index 9ad08bb..d514710 100644
--- a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/HostedConfiguration.java
+++ b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/HostedConfiguration.java
@@ -66,7 +66,7 @@ public class HostedConfiguration {
 
     static void setDefaultIfEmpty(FeatureImpl.AfterRegistrationAccessImpl access) {
         if (!ImageSingletons.contains(HostedConfiguration.class)) {
-            ClassInitializationSupport classInitializationSupport = NativeImageOptions.EagerlyInitializeClasses.getValue()
+            ClassInitializationSupport classInitializationSupport = (NativeImageOptions.EagerlyInitializeClasses.getValue() && !NativeImageOptions.DisableEagerCLInit.getValue())
                             ? new EagerClassInitialization(access.getMetaAccess())
                             : new ConservativeClassInitialization(access.getMetaAccess());
             ImageSingletons.add(RuntimeClassInitializationSupport.class, classInitializationSupport);
diff --git a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageOptions.java b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageOptions.java
index bf7aaee..29653a5 100644
--- a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageOptions.java
+++ b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageOptions.java
@@ -125,6 +125,9 @@ public class NativeImageOptions {
     @Option(help = "Initialize side-effectful application class initializers at image build time.", type = OptionType.User)//
     public static final HostedOptionKey<Boolean> EagerlyInitializeClasses = new HostedOptionKey<>(true);
 
+    @APIOption(name = "disable-eager-clinit") @Option(help = "Disable eagerly initialize classes. All classes are defaultly not eagerly initlialized.", type = OptionType.User) public static final HostedOptionKey<Boolean> DisableEagerCLInit = new HostedOptionKey<>(
+                    false);
```
But the compiled executable crashes during run time with the following messages. I don't quite understand the crash information. What does it suggest and what should I do according to this information?

```
 General Purpose Register Set Values:

  RAX 0000000000000000
  RBX 0000000000000000
  RCX 0000000003698010
  RDX 00000000015b0228
  RBP 0000000000723628
  RSI 0000000001356508
  RDI 00000000016e8e38
  RSP 00007ffdb85de398
  R8 0000000000092872
  R9 0000000000092872
  R10 0000000000092874
  R11 0000000000000014
  R12 00007fe498de66a0
  R13 00000000c0001002
  R14 0000000000e8e000
  R15 0000000003698010
  EFL 0000000000010206
  RIP 0000000000000000


JavaFrameAnchor dump:

  No anchors

TopFrame info:


VMThreads info:

VMThread 0000000003698010  STATUS_IN_JAVA (safepoints disabled)  java.lang.Thread@0x15b0228

VM Thread State for current thread 0000000003698010:

  0 (8 bytes): com.oracle.svm.jni.JNIThreadLocalEnvironment.jniFunctions = (bytes)
    0000000003698010: 0000000000000000

  8 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.pinnedTLAB = (bytes)
    0000000003698018: 0000000000000000 0000000000000000
    0000000003698028: 0000000000000000 0000000000000000


  40 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.regularTLAB = (bytes)
    0000000003698038: 00007fe499c00000 00007fe499d00000
    0000000003698048: 00007fe499c74880 0000000000000000


  72 (8 bytes): com.oracle.svm.core.genscavenge.PinnedAllocatorImpl.openPinnedAllocator = (Object) null
  80 (8 bytes): com.oracle.svm.core.heap.NoAllocationVerifier.openVerifiers = (Object) null
  88 (8 bytes): com.oracle.svm.core.jdk.IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) null
  96 (8 bytes): com.oracle.svm.core.snippets.SnippetRuntime.currentException = (Object) null
  104 (8 bytes): com.oracle.svm.core.thread.JavaThreads.currentThread = (Object) java.lang.Thread  00000000015b0228
  112 (8 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.activeTimer = (Object) null
  120 (8 bytes): com.oracle.svm.jni.JNIThreadLocalHandles.handles = (Object) null
  128 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPendingException.pendingException = (Object) null
  136 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null
  144 (8 bytes): com.oracle.svm.jni.JNIThreadOwnedMonitors.ownedMonitors = (Object) null
  152 (8 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.freeList = (Word) 0  0000000000000000
  160 (8 bytes): com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.stackBoundaryTL = (Word) 140727688273920  00007ffdb7dea000
  168 (8 bytes): com.oracle.svm.core.stack.JavaFrameAnchors.lastAnchor = (Word) 0  0000000000000000
  176 (8 bytes): com.oracle.svm.core.thread.VMThreads.IsolateTL = (Word) 15261696  0000000000e8e000
  184 (8 bytes): com.oracle.svm.core.thread.VMThreads.OSThreadIdTL = (Word) 140619832883008  00007fe49b2ff740
  192 (8 bytes): com.oracle.svm.core.thread.VMThreads.nextTL = (Word) 0  0000000000000000
  200 (4 bytes): com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.yellowZoneStateTL = (int) 1  00000001
  204 (4 bytes): com.oracle.svm.core.snippets.ImplicitExceptions.implicitExceptionsAreFatal = (int) 0  00000000
  208 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequested = (int) -52557  ffff32b3
  212 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequestedValueBeforeSafepoint = (int) 0  00000000
  216 (4 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.currentPauseDepth = (int) 0  00000000
  220 (4 bytes): com.oracle.svm.core.thread.VMOperationControl.isLockOwner = (int) 0  00000000
  224 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.safepointsDisabledTL = (int) 1  00000001
  228 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.statusTL = (int) 1  00000001

VMOperation dump:

  No VMOperation in progress

Dump Counters:


Raw Stacktrace:

  00007ffdb85de398: 00000000005e2bbe 00000000016e90d8
  00007ffdb85de3a8: 00000000015b1650 00000000016e9098
  00007ffdb85de3b8: 00000000015b1650 00000000016e8e78
  00007ffdb85de3c8: 000000000085ae78 00000000015b1678
  00007ffdb85de3d8: 0000000001356508 00000000016e8e38
  00007ffdb85de3e8: 000000000085443f 00000000015b1678
  00007ffdb85de3f8: 00000000014952f8 0000000001356508
  00007ffdb85de408: 0000000000805aef 00007fe499c72e98
  00007ffdb85de418: 0000000100b42ce3 00000000013563d8
  00007ffdb85de428: 000000000080203e 0000000001725cb8
  00007ffdb85de438: 0000000000e8e000 00007fe499c74868
  00007ffdb85de448: 00007fe499c6cba0 00000000013563d8
  00007ffdb85de458: 0000000000801dfa 00000000014555e8
  00007ffdb85de468: 00000000005e2bbe 000000010162d680
  00007ffdb85de478: 0000000100000000 000000000162d4b8
  00007ffdb85de488: 00000000015b1650 0000000001701ee8
  00007ffdb85de498: 0000000000873ee8 00000000015b1678
  00007ffdb85de4a8: 000000000134d2b0 0000000001701ea8
  00007ffdb85de4b8: 000000000085443f 000000000162d660
  00007ffdb85de4c8: 00000000005e3989 000000000134d2b0
  00007ffdb85de4d8: 00000000005e2b87 000000000162d660
  00007ffdb85de4e8: 00000000015b1650 000000000162d620
  00007ffdb85de4f8: 00000000015b1650 000000000162d498
  00007ffdb85de508: 000000000079f498 00000000015b1678
  00007ffdb85de518: 00000000014bd488 000000000162d458
  00007ffdb85de528: 000000000085443f 00000000015b1678
  00007ffdb85de538: 0000000001369f08 00000000014bd488
  00007ffdb85de548: 0000000000cbf87f 00007fe499c6c898
  00007ffdb85de558: 0000000000e8e000 00000000014bd488
  00007ffdb85de568: 0000000000cc293d 00007fe499c6c9a8
  00007ffdb85de578: 0000000000000006 0000000001364838
  00007ffdb85de588: 00000000005e2bbe 0000000100ed7f30
  00007ffdb85de598: 0000000100000000 00000000016337e8
  00007ffdb85de5a8: 00000000015b1650 000000000162d400
  00007ffdb85de5b8: 000000000079f400 00000000015b1678
  00007ffdb85de5c8: 0000000001369fc0 000000000162d3c0
  00007ffdb85de5d8: 000000000085443f 00000010015b1c48
  00007ffdb85de5e8: 0000000000ed7f50 0000000001369fc0
  00007ffdb85de5f8: 00000000005e2b87 0000000001368598
  00007ffdb85de608: 0000000000c89a17 0000000001361ef0
  00007ffdb85de618: 00000000015b1650 00000000016337c8
  00007ffdb85de628: 00000000007a57c8 00000000015b1678
  00007ffdb85de638: 00000000014b5ed8 0000000001633788
  00007ffdb85de648: 000000000085443f 0000000001450dd8
  00007ffdb85de658: 00000000013685b0 00000000014b5ed8
  00007ffdb85de668: 0000000000bde1b2 00000000015b1678
  00007ffdb85de678: 00007fe499c6c990 00000000014b5ed8
  00007ffdb85de688: 00007fe499c642c0 00007fe499c65428
  00007ffdb85de698: 00007fe499c653e8 00007fe499c6c7b8
  00007ffdb85de6a8: 0000000000c1823b 000000000133c5d8
  00007ffdb85de6b8: 00000000008470e8 0000000000000000
  00007ffdb85de6c8: 0000000000ed34e0 000000000146bf78
  00007ffdb85de6d8: 0000000000bcb6e9 00007fe499c64270
  00007ffdb85de6e8: 000000000133c5d8 00007fe498dd6cc0
  00007ffdb85de6f8: 00007fe499c642c0 0000000000bcb5f5
  00007ffdb85de708: 00007fe499c6c7b8 0000000001360d30
  00007ffdb85de718: 00007fe499c64270 0000000000e8e000
  00007ffdb85de728: 00007fe499c642c0 00007fe499c64cc0
  00007ffdb85de738: 0000000000be699f 0000000001632ab8
  00007ffdb85de748: 00000000007a4ab8 00000000015b1678
  00007ffdb85de758: 00000000014b6968 00007fe499c64cc0
  00007ffdb85de768: 00000000014b6a40 00007fe499c64270
  00007ffdb85de778: 00007fe499c50fd8 00007fe499c64108
  00007ffdb85de788: 0000000000bfefa9 0000000001360bb0

Stacktrace Stage1:


Full Stacktrace:


[Native image heap boundaries:
  ReadOnly Primitives: 0xe8e008 .. 0x133b910
  ReadOnly References: 0x133c4d8 .. 0x14f2bf8
  Writable Primitives: 0x14f3000 .. 0x15aa250
  Writable References: 0x15aa2e0 .. 0x17631c0]


[Heap:
  [Young generation:
    [youngSpace:
      aligned: 0/0 unaligned: 0/0]]
  [Old generation:
    [fromSpace:
      aligned: 0/0 unaligned: 0/0]
    [toSpace:
      aligned: 0/0 unaligned: 0/0]
    [pinnedFromSpace:
      aligned: 0/0 unaligned: 0/0]
    [pinnedToSpace:
      aligned: 0/0 unaligned: 0/0]]
  [Unused:
    aligned: 0/0]]

Use runtime option -R:-InstallSegfaultHandler if you don't want to use SubstrateSegfaultHandler.


```

**Comment by vjovanov** [comment]
Yes, in a couple of days. We will have a flag `--initialize-at-run-time` and `--initialize-at-build-time` which will allow control over how things get initialized.

**Comment by vjovanov** [comment]
It should work now without adding any flags.

**Comment by ziyilin** [comment]
Tried with different combinations of initilization options. I found delay all class initialization to runtime is still not working. 

**==Eager class initialization==**
With following options, both native image building and running are good.
```
SVM_OPT="${SVM_OPT} --initialize-at-build-time"
SVM_OPT="${SVM_OPT} --initialize-at-run-time=io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator"
SVM_OPT="${SVM_OPT} --initialize-at-run-time=io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator"
SVM_OPT="${SVM_OPT} --initialize-at-run-time=io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator"
SVM_OPT="${SVM_OPT} --initialize-at-run-time=io.netty.handler.ssl.JdkNpnSslEngine"
SVM_OPT="${SVM_OPT} --initialize-at-run-time=io.netty.handler.ssl.JdkAlpnSslEngine"
SVM_OPT="${SVM_OPT} --initialize-at-run-time=io.netty.util.internal.JavassistTypeParameterMatcherGenerator"
SVM_OPT="${SVM_OPT} --initialize-at-run-time=com.alibaba.fastjson.serializer.JodaCodec"

SVM_OPT="${SVM_OPT} --rerun-class-initialization-at-runtime=io.netty.handler.ssl.util.SelfSignedCertificate"
SVM_OPT="${SVM_OPT} --rerun-class-initialization-at-runtime=io.netty.handler.ssl.util.ThreadLocalInsecureRandom"
SVM_OPT="${SVM_OPT} --rerun-class-initialization-at-runtime=com.alibaba.fastjson.serializer.SerializeConfig"
SVM_OPT="${SVM_OPT} --rerun-class-initialization-at-runtime=com.alibaba.fastjson.parser.ParserConfig"
SVM_OPT="${SVM_OPT} --rerun-class-initialization-at-runtime=org.apache.rocketmq.client.impl.MQClientAPIImpl"
SVM_OPT="${SVM_OPT} -H:+PrintClassInitialization"
```
**==No Settings==**
Comment out all above settings, as it is said in previous post:

> It should work now without adding any flags.

I got some warnings during building such as:
`Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of io.netty.util.internal.PlatformDependent. Detailed failure reason(s): Could not determine the field where the value produced by the call to sun.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.`
And the native image crashed with the same messages I posted earlier.


**==Setting Runtime Class Initialization==**

When I set explicitly set initialize all packages during runtime with

`SVM_OPT="${SVM_OPT} --initialize-at-run-time"`

It failed at build time with 
```
Fatal error: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.debug.GraalError: should not reach here: Classes can only be initialized using methods in ClassInitializationFeature: com.oracle.svm.core.hub.ClassInitializationInfo
        at parsing com.oracle.svm.core.hub.ClassInitializationInfo.isInitialized(ClassInitializationInfo.java:138)
        at parsing com.oracle.svm.core.hub.DynamicHub.ensureInitialized(DynamicHub.java:436)
        at parsing org.graalvm.compiler.replacements.SnippetCounter.inc(SnippetCounter.java:137)
        at parsing org.graalvm.compiler.replacements.BoxingSnippets.booleanValueOf(BoxingSnippets.java:60)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:460)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:289)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:427)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:109)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.debug.GraalError: should not reach here: Classes can only be initialized using methods in ClassInitializationFeature: com.oracle.svm.core.hub.ClassInitializationInfo
        at parsing com.oracle.svm.core.hub.ClassInitializationInfo.isInitialized(ClassInitializationInfo.java:138)
        at parsing com.oracle.svm.core.hub.DynamicHub.ensureInitialized(DynamicHub.java:436)
        at parsing org.graalvm.compiler.replacements.SnippetCounter.inc(SnippetCounter.java:137)
        at parsing org.graalvm.compiler.replacements.BoxingSnippets.booleanValueOf(BoxingSnippets.java:60)
        at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2621)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:85)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3421)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
at org.graalvm.compiler.java.BytecodeParser.parseAndInlineCallee(BytecodeParser.java:2641)
        at org.graalvm.compiler.java.BytecodeParser.inline(BytecodeParser.java:2542)
        at org.graalvm.compiler.java.BytecodeParser.tryInline(BytecodeParser.java:2288)
        at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1775)
        at org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1638)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1588)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1573)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5255)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
        at org.graalvm.compiler.java.BytecodeParser.parseAndInlineCallee(BytecodeParser.java:2641)
        at org.graalvm.compiler.java.BytecodeParser.inline(BytecodeParser.java:2542)
        at org.graalvm.compiler.java.BytecodeParser.tryInline(BytecodeParser.java:2288)
        at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1775)
        at org.graalvm.compiler.java.BytecodeParser.handleReplacedInvoke(BytecodeParser.java:1705)
        at com.oracle.svm.hosted.phases.SubstrateClassInitializationPlugin.apply(SubstrateClassInitializationPlugin.java:79)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1525)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1509)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5257)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
        at org.graalvm.compiler.java.BytecodeParser.parseAndInlineCallee(BytecodeParser.java:2641)
        at org.graalvm.compiler.java.BytecodeParser.inline(BytecodeParser.java:2542)
        at org.graalvm.compiler.java.BytecodeParser.tryInline(BytecodeParser.java:2288)
        at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1775)
        at org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1638)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1588)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1573)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5255)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
 at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:838)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at org.graalvm.compiler.replacements.ReplacementsImpl$GraphMaker.buildInitialGraph(ReplacementsImpl.java:561)
        at com.oracle.svm.hosted.code.SubstrateGraphMaker.buildInitialGraph(SubstrateGraphMaker.java:62)
        at org.graalvm.compiler.replacements.ReplacementsImpl$GraphMaker.makeGraph(ReplacementsImpl.java:435)
        at org.graalvm.compiler.replacements.ReplacementsImpl.makeGraph(ReplacementsImpl.java:376)
        at org.graalvm.compiler.replacements.ReplacementsImpl.makeGraph(ReplacementsImpl.java:394)
        at com.oracle.svm.core.graal.meta.SubstrateReplacements.registerSnippet(SubstrateReplacements.java:226)
        at org.graalvm.compiler.replacements.SnippetTemplate$AbstractTemplates.snippet(SnippetTemplate.java:678)
        at org.graalvm.compiler.replacements.SnippetTemplate$AbstractTemplates.snippet(SnippetTemplate.java:665)
        at org.graalvm.compiler.replacements.BoxingSnippets$Templates.<init>(BoxingSnippets.java:194)
        at org.graalvm.compiler.replacements.DefaultJavaLoweringProvider.initialize(DefaultJavaLoweringProvider.java:180)
        at com.oracle.svm.core.graal.meta.SubstrateBasicLoweringProvider.setConfiguration(SubstrateBasicLoweringProvider.java:115)
        at com.oracle.svm.hosted.NativeImageGenerator.registerReplacements(NativeImageGenerator.java:1208)
        at com.oracle.svm.hosted.NativeImageGenerator.initializeBigBang(NativeImageGenerator.java:902)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:842)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:443)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.graalvm.compiler.debug.GraalError: should not reach here: Classes can only be initialized using methods in ClassInitializationFeature: com.oracle.svm.core.hub.ClassInitializationInfo
        at org.graalvm.compiler.debug.GraalError.shouldNotReachHere(GraalError.java:51)
        at com.oracle.graal.pointsto.meta.AnalysisType.initialize(AnalysisType.java:706)
        at org.graalvm.compiler.java.BytecodeParser.initialize(BytecodeParser.java:4223)
        at org.graalvm.compiler.java.BytecodeParser.lookupField(BytecodeParser.java:4292)
        at org.graalvm.compiler.java.BytecodeParser.lookupField(BytecodeParser.java:4280)
        at org.graalvm.compiler.java.BytecodeParser.genGetField(BytecodeParser.java:4634)
        at org.graalvm.compiler.java.BytecodeParser.loadLocalObject(BytecodeParser.java:3960)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5118)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
        ... 63 more
```
You can reproduce it with my forked RocketMQ (https://github.com/ziyilin/rocketmq). 
My Graal is updated to master b99c1a73a282327ba4f8ea306e741a2347aaf9c5

I have also changed Target_java_lang_ClassLoader.java a little:
```
diff --git a/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_ClassLoader.java b/
index adcaa7c..c638fc6 100644
--- a/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_ClassLoader.java
+++ b/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_ClassLoader.java
@@ -43,6 +43,7 @@ import com.oracle.svm.core.hub.DynamicHub;
 import com.oracle.svm.core.jdk.JavaLangSubstitutions.ClassLoaderSupport;
 import com.oracle.svm.core.snippets.KnownIntrinsics;
 import com.oracle.svm.core.util.VMError;
+import java.security.ProtectionDomain;

 @TargetClass(ClassLoader.class)
 @Substitute
@@ -132,6 +133,17 @@ public final class Target_java_lang_ClassLoader {
     }

     @Substitute
+    Class<?> defineClass(String name, byte[] b, int off, int len,
+                    ProtectionDomain protectionDomain)
+                    throws ClassFormatError {
+       try {
+            return ClassForNameSupport.forName(name);
+        } catch (ClassNotFoundException e) {
+            throw new ClassFormatError("class "+ name + " has not been prepared.");
+        }
+    }
+
+    @Substitute
     @SuppressWarnings("unused")
     static void checkClassLoaderPermission(ClassLoader cl, Class<?> caller) {
     }
```

**Comment by vjovanov** [comment]
Nice catch. When you do that classes from the JDK start getting delayed and they should not as Native Image does not really support that. I will make the fix that the JDK is also treated through the package system (currently it is initialized differently). 

To achieve what you want you can simply leave no flags on the command line. That will initialize at runtime any non-JDK class with side-effects.

**Comment by vjovanov** [comment]
I will have a fix for this soon. JDK will still be initialized at build-time, but you will be able to set the default for the whole hierarchy.

Until then, you can simply do `--initialize-at-run-time=<csv-of-all-your-packages>`.

**Comment by dmlloyd** [comment]
I think this should be reopened as the original issue isn't fixed yet?  We have a similar problem, but we're registering our eager initializations via the `RuntimeClassInitializationSupport` image singleton from an automatic feature.  None of our registrations seem to be taking effect.

**Comment by dmlloyd** [comment]
Hey @vjovanov, it's been a couple of weeks on this; any progress or new info?

**Comment by vjovanov** [comment]
I will finish this issue this week. I can push a temporary branch if you want to try it out.

**Comment by dmlloyd** [comment]
That would be great, thanks.

**Comment by emmanuelbernard** [comment]
Hey @vjovanov ,

Assuming the branch works, how soon will we see a version with that patch. 
Right now we are not going to offer support for GraalVM 19 for Quarkus. This is too much of a breaking change for us or anything that embrace the idiomatic GraalVM approach. 

Emmanuel

**Comment by vjovanov** [comment]
I didn't know it is so urgent. I can increase priority and get this merged tomorrow.

The new beta release should be at the beginning of June.

**Comment by emmanuelbernard** [comment]
Thanks @vjovanov 
By beta you mean 19.1 or 19.1 beta or 20 beta ?
Of course for us 19.1 would be ideal but I don’t remember if you had such an aggressive schedule.

**Comment by vjovanov** [comment]
I mean 20 beta.

The branch that should allow this is feature is here: 

  https://github.com/vjovanov/graal/tree/fix/order-of-initialization-rules

Now, I am wondering why do you need this for Quarkus? This feature only prevents native-image from initializing classes that were considered safe. This kind of behavior was never possible before so it should not be breaking anything in your build.

Maybe there is a deeper problem that we need to solve.

**Comment by dmlloyd** [comment]
What we're encountering is that we're trying to set the default to be build-time initialization, but it is then ignoring classes which are subsequently registered by way of a custom auto-feature using the image singleton `com.oracle.svm.hosted.classinitialization.ClassInitializationSupport`.  So basically no classes are run-time initialized.

**Comment by vjovanov** [comment]
Can you point me to the code? 

Depends on which classes are configured. They could be already initialized by some other means. If the class is already initialized and you use `com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization#initializeAtRunTime(java.lang.Class<?>, java.lang.String)` the image build  should fail with `Class is already initialized, so it is too late to register delaying class initialization...`.

Also, I would not use `com.oracle.svm.hosted.classinitialization.ClassInitializationSupport` but rather `org.graalvm.nativeimage.hosted.RuntimeClassInitialization`.

**Comment by dmlloyd** [comment]
> Can you point me to the code?

At the moment the class is generated.  The in-tree version works against the rc16 APIs:

https://github.com/quarkusio/quarkus/blob/0.15/core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateAutoFeatureStep.java#L66

It's a bit difficult to unwind but basically we're creating a `beforeAnalysis` method on a `AutomaticFeature` which registers each class.  The in-progress branch for GraalVM 19 is a little different:

https://github.com/dmlloyd/quarkus/blob/graal-19/core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateAutoFeatureStep.java#L80

In this branch we've switched to using `RuntimeClassInitializationSupport` for reasons explained below.

> Depends on which classes are configured. They could be already initialized by some other means. If the class is already initialized and you use `com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization#initializeAtRunTime(java.lang.Class<?>, java.lang.String)` the image build should fail with `Class is already initialized, so it is too late to register delaying class initialization...`.

OK we don't see this message, so I think then that must not be the problem.

> Also, I would not use `com.oracle.svm.hosted.classinitialization.ClassInitializationSupport` but rather `org.graalvm.nativeimage.hosted.RuntimeClassInitialization`.

Using `RuntimeClassInitialization` is not an option for us at the moment because we need to register some classes for re-running initialization.  Also I mis-pasted, we are using `org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport` not `com.oracle.svm.hosted.classinitialization.ClassInitializationSupport` in our GraalVM 19 tree.

So basically it seems like these classes are either being ignored, or else there's something wrong with how the registration works in terms of whether packages or classes take precedence and under what conditions.

I'll do another try with your branch just to see what happens; maybe we'll get another data point.

**Comment by dmlloyd** [comment]
It looks like your branch didn't make a difference for us. I'm going to run a few more tests though.

**Comment by vjovanov** [comment]
Yes, my branch will not change anything. If give me an easy way to debug I will gladly see what is the issue. We need to fix this as soon as possible.

By looking at the code I don't see how this could be possible. Calling `initializeAtRunTime` directly remembers the result of initialization.

**Comment by dmlloyd** [comment]
I guess the easiest way to reproduce it would be to check out this branch:

https://github.com/dmlloyd/quarkus/tree/graal-19

Set your `JAVA_HOME` and `GRAALVM_HOME` environment variables to point to your GraalVM 19 release (and make sure it's on your path obviously).  Make sure you have Maven installed (3.6.0 or later) and type: `mvn install -DskipTests -Dnative`.  It should take around 2 to 3 minutes to get to the point where you can see the error, which is something like:

```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option -H:ClassInitialization=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 
	at parsing io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(AjpServerRequestConduit.java:195)
Call path from entry point to io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(ByteBuffer): 
	at io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(AjpServerRequestConduit.java:183)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:703)
	[...]
```

The problem is that we've registered `AjpServerRequestConduit` as run-time initialized in the aforementioned auto feature, so this error should not occur.

**Comment by dmlloyd** [comment]
Hang on... if there's an error loading or running an automatic feature class, is that logged anywhere?

**Comment by dmlloyd** [comment]
I fixed a signature error in the generated class that should have caused an `Error` to be thrown at run time.  But it didn't make any difference so I'm wondering if there's some other error in the auto feature that is simply not logged.

**Comment by vjovanov** [comment]
Can you put a breakpoint in the `beforeAnalysis` of that feature? That would show if it gets executed.

**Comment by dmlloyd** [comment]
I added a breakpoint... and it was never run.  It turns out the `Feature` interface changed packages.  GraalVM silently skipped the feature because it couldn't be instantiated.  I think we have a few types in here that changed packages; now that I have it recognizing the feature, our try/catch is showing all the problems.

I think this issue *might* be solved... doing some additional testing now.

**Comment by dmlloyd** [comment]
Yes, I think it's fixed.  Thanks for giving me the help I needed, even if it wasn't the help I expected!

**Comment by cstancu** [comment]
@dmlloyd can we close this issue?

**Comment by dmlloyd** [comment]
Yes, go ahead.
