### ISSUE TITLE
[truffle-dsl] Problem with execute methods with varargs

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1210]
### Example code
```java
public class Example {
    public abstract class ArgumentNode extends Node {
        public abstract Object executeRead(VirtualFrame frame);
    }

    @NodeChild(value = "arguments", type = ArgumentNode[].class)
    public abstract static class AbstractNode extends Node {

        public abstract Object executeWithArguments(VirtualFrame frame, Object... arguments);

        public abstract Object executePrimitive(VirtualFrame frame);
    }

    protected abstract static class ExampleNode extends AbstractNode {

        @Specialization(limit = "1")
        protected static final boolean doIsBoolean(final Object receiver,
                        @CachedLibrary("receiver") final InteropLibrary functions) {
            return functions.isBoolean(receiver);
        }
    }
}
```

### Generated code
```java
// ...
 @TruffleBoundary
private Object isBoolean1Boundary(int state, Object arguments0Value) {
    Node prev_ = NodeUtil.pushEncapsulatingNode(this);
    try {
        /** The next line throw compilation error: */
        return ExampleNode.doIsBoolean(args[0], (INTEROP_LIBRARY_.getUncached(args[0])));
    } finally {
        NodeUtil.popEncapsulatingNode(prev_);
    }
}
// ...
```

### Observations
- Problem fixed when `executeWithArguments` is removed
- Problem still there if `executePrimitive` and `@NodeChild` is removed
- Problem fixed when `doIsBoolean(final TruffleObject receiver,` is used

/cc @chumer

**Comment by fniephaus** [comment]
As a workaround, I seem to be able to use:
```java
@Specialization
protected static final boolean doIsBoolean(final Object receiver,
                @CachedLibrary(limit = "1") final InteropLibrary functions) {
    return functions.isBoolean(receiver);
}
```

**Comment by chumer** [comment]
Seems like I missed that combination in the test. Thanks for the report.

**Comment by boris-spas** [comment]
Tracked internally as Issue GR-20916.

**Comment by chumer** [comment]
I've already fixed this a while ago. At least the problem is no longer reproducible.

**Comment by fniephaus** [comment]
Thanks for the update, that means I can finally clean up some stuff...great!

**Comment by fniephaus** [comment]
I just gave the current master a try and it seems this is still happening. Here's a reproducer:

```java
@GenerateNodeFactory
protected abstract static class ExampleNode extends Node {

    public abstract Object executeWithArguments(VirtualFrame frame, Object... arguments);

    @Specialization(limit = "3")
    protected static final boolean doIsInstantiable(@SuppressWarnings("unused") final Object receiver, final Object object,
                    @CachedLibrary("object") final InteropLibrary lib) {
        return lib.isInstantiable(object);
    }
}
```

**Comment by boris-spas** [comment]
Should this be reopened?

**Comment by fniephaus** [comment]
Yes, please. I can't reopen it.

**Comment by chumer** [comment]
Indeed. Still reproducible this way :-(.

**Comment by chumer** [comment]
Fixed as part of https://github.com/oracle/graal/commit/8baf365e6ade02a0e375bc998c5508222940e2be

**Comment by fniephaus** [comment]
Thanks, @chumer!

**Comment by Dufgui** [comment]
I think I still experiment this bug in 21.3.
I try to create a builtin with varargs

https://github.com/Dufgui/graaltcl/blob/main/language/src/main/java/com/oracle/truffle/tcl/builtins/TclListBuiltin.java

But it not works. The TclListBuiltinFactory take only the first arg, no ?
```
@Override
    public TclListBuiltin createNode(Object... arguments) {
        if (arguments.length == 1 && (arguments[0] == null || arguments[0] instanceof TclExpressionNode[])) {
            return create((TclExpressionNode[]) arguments[0]);
        } else {
            throw new IllegalArgumentException("Invalid create signature.");
        }
    }
```


 I don't find any entry in documentation in https://www.graalvm.org/graalvm-as-a-platform/language-implementation-framework/

I hope I am wrong and I badly use the truffle api

**Comment by chumer** [comment]
@Dufgui  

A concrete builtin node *always* has a fixed set of arguments. So having a varargs parameter in @Fallback or @Specialization method does not have meaning. It will just set the first parameter to be checked and cast to an array type.

Since you use in TclBuiltinNode :
```
@NodeChild(value = "arguments", type = TclExpressionNode[].class)
```
The first parameter in the factory is expected to be TclExpressionNode[]. Note that NodeFactory#createNode has a generic signature to create any node.

Also it is very unusual to have a node with only a @Fallback specialization. I'd recommend to turn it into a regular @Specialization.
