### ISSUE TITLE
[Native Image] "native-image-agent" fails to generate complete reflection for classes without default constructor when using gson for de-serialization

### ISSUE THREAD

**Issue by Sasuke214** [oracle/graal#12749]
### Context

We are migrating our springboot application to run it as a Graal Native Image. Upon using `native-image-agent` for generation of reflection, there are multiple classes present in my project which are coming from external libraries which i do not own and cannot make changes to.

Those classes are similar to `SSOGetTokenResponse` which i have added in the example repo which can be used to reproduce the issue. Below is the sample class:

`public class SSOGetTokenResponse {
    private String accessToken;

    public String getAccessToken() {
        return this.accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public SSOGetTokenResponse(String accessToken) {
        this.accessToken = accessToken;
    }
}`

I use Gson to de-serialize the payload.

`
new Gson().fromJson("{\"access_token\": \"apple\"}", SSOGetTokenResponse.class)
`

It works fine upon running it in JVM mode and running jar with native-image-agent for reflection generation, it generates

`
{
  "name":"org.example.dtos.SSOGetTokenResponse",
  "allDeclaredFields":true,
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
`

### Issue

The problem is when i generate a native image and run it, it throws below error:
`
java.lang.IllegalArgumentException: Type org.example.dtos.SSOGetTokenResponse is instantiated reflectively but was never registered. Register the type by adding "unsafeAllocated" for the type in reflect-config.json.
`

currently as a workaround, i have added "unsafeAllocated" to generated reflection config manually and it works post that but would be awesome if we can figure out and fix it in the tool itself somehow

### GraalVM Version

java 21.0.8 2025-07-15 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.8+12.1 (build 21.0.8+12-LTS-jvmci-23.1-b72)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.8+12.1 (build 21.0.8+12-LTS-jvmci-23.1-b72, mixed mode, sharing)

### Operating System and Version

Darwin Kernel Version 24.4.0: Fri Apr 11 18:32:50 PDT 2025; root:xnu-11417.101.15~117/RELEASE_ARM64_T6041 arm64

### Troubleshooting Confirmation

- [x] I tried the suggestions in the [troubleshooting guide](https://www.graalvm.org/latest/reference-manual/native-image/guides/troubleshoot-run-time-errors/).

### Run Command

./mvnw -Pnative -DskipTests native:compile

### Expected Behavior

Generates complete reflection for the provided class

### Actual Behavior

Generates reflection for the provided class but doesn't have "unsafeAllocated" or any way to instanciate that class

### Steps to Reproduce

1. Clone the repo https://github.com/Sasuke214/graalvm-demo
2. Run `sdk use java 21.0.8-graal`
3. Run `./mvnw -Pnative -DskipTests native:compile`
4. Run `./target/Graal-JS`

### Run-Time Log Output and Error Messages

java.lang.IllegalArgumentException: Type org.example.dtos.SSOGetTokenResponse is instantiated reflectively but was never registered. Register the type by adding "unsafeAllocated" for the type in reflect-config.json.

**Comment by oubidar-Abderrahim** [comment]
Hi, this particular issue was already resolved in the latest GraalVM 25.0.1, please upgrade to that version, thank you

**Comment by Sasuke214** [comment]
@oubidar-Abderrahim upgraded to GraalVM 25.0.1. But still seeing the same issue:

Generated Reflection inside `rechability-metadata.json`
`
    {
      "type": "org.example.dtos.SSOGetTokenResponse"
    }
`

**Error**
`
java.lang.IllegalArgumentException: Type org.example.dtos.SSOGetTokenResponse is instantiated reflectively but was never registered. Register the type by adding "unsafeAllocated" for the type in reflect-config.json.
`

```
➜  graalvm-demo git:(main) ✗ java --version
java 25.0.1 2025-10-21 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 25.0.1+8.1 (build 25.0.1+8-LTS-jvmci-b01)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 25.0.1+8.1 (build 25.0.1+8-LTS-jvmci-b01, mixed mode, sharing)
```

**Steps to reproduce:**
1. Clone the repo https://github.com/Sasuke214/graalvm-demo
2. Run sdk use java 25.0.1-graal
3. Run ./mvnw -Pnative -DskipTests native:compile
4. Run ./target/Graal-JS

**Comment by Sasuke214** [comment]
@oubidar-Abderrahim  can u please re-open this issue as it's happening in the suggested version as well
