### ISSUE TITLE
Minecraft 1.18 Initial World Generation Fails

### ISSUE THREAD

**Issue by estrogently** [oracle/graal#4071]
**Describe the issue**
Initial world generation on a Minecraft 1.18 server fails with one or more `java.lang.IllegalStateException: stream has already been operated upon or closed` errors, after which it hangs indefinitely. This issue does not occur on OpenJDK 17.

**Steps to reproduce the issue**
1. Download the [1.18 server jar](https://launcher.mojang.com/v1/objects/3cf24a8694aca6267883b17d934efacc5e44440d/server.jar)
2. Create a `eula.txt` file containing `eula=true`
3. Create a `server.properties` file containing `level-seed=1423185990`
2. `java -jar server.jar`

**Describe GraalVM and your environment:**
 - GraalVM version: **EE 21.3.0**
 - JDK major version: **17**
 - OS: **Oracle Linux 8**
 - Architecture: **aarch64**

**More details**
The error happens at different places and in different amounts during the world generation process, likely due to the world generation itself being random.
Logs from 2 instances of this bug:
1. [Happening only once during generation](https://gist.github.com/estrogently/f11faf34a5b11c3e044c42dd5039116d)
2. [Happening multiple times during generation](https://gist.github.com/estrogently/ce88b4ad678a3350c6422eb3467c2e40)

**Comment by smallshen** [comment]
It also happens on client

**Comment by gergo-** [comment]
Thanks for the report @estrogently . I can reproduce a problem which may cause the error you're seeing. Tracking this internally as GR-35446.

**Comment by gergo-** [comment]
I fixed the internal compiler error that I found, but now I'm not convinced anymore that it's related to this exception and hang. I haven't been able to reproduce those so far.

@estrogently on the remote chance that this is the same problem, could you try running with the `-Dgraal.VectorizeGather=false` flag, i.e., `java -Dgraal.VectorizeGather=false -jar server.jar`?
Are you running on an Oracle Cloud instance with the pre-installed GraalVM EE? I know you specified the versions above, but just to be sure, could you also list the outputs of `java -version` and `java -Xinternalversion`?

@smallshen Could you provide more detailed reproduction instructions please, with a link to the actual client you're running, and the GraalVM version and platform?

**Comment by estrogently** [comment]
Running it with that flag sadly does not fix it.
For reproducibility's sake, adding `level-seed=1423185990` to the server.properties file (and removing the "world" folder, if one is already present) consistently gets it to occur near the end of the "preparing spawn area" stage for me.

> Are you running on an Oracle Cloud instance with the pre-installed GraalVM EE?

I'm running on Oracle Cloud (a 4-core arm A1.Flex), with the GraalVM EE JDK from the included repositories (`graalvm21-ee-17-jdk`, version `21.3.0-1.el8`, from `@ol8_oci_included`).

```
$ java -version
Java(TM) SE Runtime Environment GraalVM EE 21.3.0 (build 17.0.1+12-LTS-jvmci-21.3-b05)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 21.3.0 (build 17.0.1+12-LTS-jvmci-21.3-b05, mixed mode, sharing)
$ java -Xinternalversion
Java HotSpot(TM) 64-Bit Server VM (17.0.1+12-LTS-jvmci-21.3-b05) for linux-aarch64 JRE (17.0.1+12-LTS-jvmci-21.3-b05), built on Oct 16 2021 12:28:33 by "buildslave" with gcc 10.3.0```

**Comment by gergo-** [comment]
Thanks for this information! With the seed I was able to reproduce this in about half of the runs. Reducing the active cores to 4 (I was testing on a 32-core machine) makes it happen every time. This doesn't seem to be specific to AArch64. I'll investigate further.

**Comment by gergo-** [comment]
`-Dgraal.OptDuplication=false` should work around this for now.

**Comment by smallshen** [comment]
> @smallshen Could you provide more detailed reproduction instructions please, with a link to the actual client you're running, and the GraalVM version and platform?

Install Minecraft and set the GraalVM as the JVM. 
You can also setup a fabric project and use it in ide.
https://fabricmc.net/wiki/start

GraalVM version: 17 EE 21.3.0

The word generation is the same on the server and client since the client is just a local server

**Comment by davleopo** [comment]
Thanks everybody for the input! We identified the problem, and the fix will land in 22.0.0 .

**Comment by Sxtanna** [comment]
> Thanks everybody for the input! We identified the problem, and the fix will land in 22.0.0 .

Hello, could you confirm this fix was implemented by closing this and attaching a reference to where it was fixed?

**Comment by davleopo** [comment]
This was fixed by https://github.com/oracle/graal/commit/eea09ec5778 .
