### ISSUE TITLE
[22.0.0] Duplicate classes in `org.graalvm.js:js` causing troubles with module-path and classpath

### ISSUE THREAD

**Issue by boris-petrov** [oracle/graal#4236]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **22.0.0**
 - CE or EE: **CE**
 - JDK version: **JDK17**
 - OS and OS Version: **Arch Linux 5.16.1-arch1-1**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
 OpenJDK 64-Bit Server VM (17.0.1+12) for linux-amd64 JRE (17.0.1+12), built on Oct 23 2021 15:46:46 by "builduser" with gcc 11.1.0
```

**Have you verified this issue still happens when using the latest snapshot?**
No.

**Describe the issue**
Updating to 22.0.0 caused my integration tests to fail with:

```
Java::JavaLang::IllegalAccessError:
            class nu.validator.checker.NormalizationChecker (in unnamed module @0x5b132063) cannot access class com.ibm.icu.text.UnicodeSet (in module org.graalvm.js) because module org.graalvm.js does not export com.ibm.icu.text to unnamed module @0x5b132063
          # nu.validator.checker.NormalizationChecker.<clinit>(nu/validator/checker/NormalizationChecker.java:69)
          # nu.validator.validation.SimpleDocumentValidator.setUpValidatorAndParsers(nu/validator/validation/SimpleDocumentValidator.java:319)
```

I see that the `org.graalvm.js:js` artifact since version 22 contains the `com.ibm.icu` namespace and hence I get that error.

**Code snippet or code repository that reproduces the issue**

`build.gradle`:
```gradle
plugins {
	id 'application'
}

repositories {
	mavenCentral()
}

configurations {
	graal
}

ext.graalVmVersion = '22.0.0'

dependencies {
	compileOnly "org.graalvm.sdk:graal-sdk:$graalVmVersion"

	implementation 'nu.validator:validator:20.7.2'

	graal "org.graalvm.compiler:compiler:$graalVmVersion"
	graal "org.graalvm.compiler:compiler-management:$graalVmVersion"
	graal "org.graalvm.sdk:graal-sdk:$graalVmVersion"
	graal "org.graalvm.truffle:truffle-api:$graalVmVersion"
	graal "org.graalvm.js:js:$graalVmVersion"
}

def graalCompilerDir = "$buildDir/graal-compiler"

application {
	mainClass = 'graal.test.App'
	applicationDefaultJvmArgs = [
		'-XX:+UnlockExperimentalVMOptions',
		'-XX:+EnableJVMCI',
		'-XX:-UseJVMCICompiler',
		"--module-path=$graalCompilerDir",
		"--upgrade-module-path=$graalCompilerDir",
	]
}

tasks.register('prepareGraalCompiler', Copy) {
	doFirst {
		delete graalCompilerDir
	}

	into graalCompilerDir
	from configurations.graal
}

tasks.named('run').configure {
	dependsOn prepareGraalCompiler
}
```

`src/main/java/graal/test/App.java`:
```java
package graal.test;

import nu.validator.client.EmbeddedValidator;
import nu.validator.validation.SimpleDocumentValidator;
import nu.validator.xml.SystemErrErrorHandler;

public class App {
	public static void main(String[] args) throws Exception {
		var validator = new SimpleDocumentValidator();
		validator.setUpMainSchema(EmbeddedValidator.SCHEMA_URL, new SystemErrErrorHandler());
		validator.setUpValidatorAndParsers(null, true, false);
	}
}
```

**Steps to reproduce the issue**
```
gradle run
```

Setting `graalVmVersion` to `21.3.0` fixes the issue.

**Expected behavior**
No error.

**Additional context**
[Slack discussion](https://graalvm.slack.com/archives/CN9L59P61/p1642580818012700).

cc @chumer

**Comment by boris-petrov** [comment]
This is still the case with version `22.1.0`. Any suggestions/solutions? cc @woess

**Comment by boris-petrov** [comment]
The same issue appears with `21.3.2` too. The last working version is `21.3.1`.

**Comment by woess** [comment]
We'll try to address the problem that the js artifact contains icu4j in 22.2.0; but even when that is fixed, there can still be library conflicts.

I would suggest to use a [GraalVM](https://www.graalvm.org/downloads/) (and remove the explicit graal dependencies). In that configuration, you should not into any such issues.

**Comment by woess** [comment]
Should be fixed by excluding icu4j from the regex and js jar files (https://github.com/oracle/graal/commit/85d21cdf702f0d6f11893af03cdf3a0d8e8107c1).

**Comment by boris-petrov** [comment]
@woess thank you for the fix! However, it doesn't seem to fix the whole problem. I've updated the original post - I've updated Graal's version to 22.2.0 and the Java file to add a couple of more method calls. This now fails with:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'boolean com.ibm.icu.lang.UCharacter.isHighSurrogate(char)'
	at nu.validator.checker.NormalizationChecker.startsWithComposingChar(NormalizationChecker.java:150)
	at nu.validator.checker.NormalizationChecker.startElement(NormalizationChecker.java:354)
	at com.thaiopensource.xml.sax.ForkContentHandler.startElement(Unknown Source)
	at com.thaiopensource.xml.sax.ForkContentHandler.startElement(Unknown Source)
	at com.thaiopensource.xml.sax.ForkContentHandler.startElement(Unknown Source)
	at com.thaiopensource.xml.sax.ForkContentHandler.startElement(Unknown Source)
	at com.thaiopensource.xml.sax.ForkContentHandler.startElement(Unknown Source)
	at com.thaiopensource.xml.sax.ForkContentHandler.startElement(Unknown Source)
	at nu.validator.xml.CombineContentHandler.startElement(CombineContentHandler.java:167)
	at nu.validator.saxtree.TreeParser.startElement(TreeParser.java:186)
	at nu.validator.saxtree.Element.visit(Element.java:102)
	at nu.validator.saxtree.TreeParser.parse(TreeParser.java:90)
	at nu.validator.htmlparser.sax.HtmlParser.parse(HtmlParser.java:413)
	at nu.validator.xml.WiretapXMLReaderWrapper.parse(WiretapXMLReaderWrapper.java:158)
	at nu.validator.validation.SimpleDocumentValidator.checkAsHTML(SimpleDocumentValidator.java:532)
	at nu.validator.validation.SimpleDocumentValidator.checkHtmlInputSource(SimpleDocumentValidator.java:405)
	at graal.test.App.main(App.java:19)
```

Again, setting `graalVmVersion` to `21.3.0` fixes the issue.

**Comment by boris-petrov** [comment]
So actually this is caused by conflicting versions of `icu4j` and it's not a problem in GraalVM. Sorry for the confusion!
