### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest

### ISSUE THREAD

**Issue by dariusf** [oracle/graal#454]
Encountered this trying to build a native image with the current master:

```sh
mx native-image --verbose -H:+ReportUnsupportedElementsAtRuntime -jar app.jar
```

`app.jar` is a (nontrivial) fat JAR created with Maven Shade. Let me know if I can provide any other useful information.

```
   classlist: 343,746.89 ms
       (cap):   3,785.04 ms
       setup:  15,238.60 ms
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/test/lib/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/test/srcclr-3.0.3-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
    analysis: 356,936.42 ms
error: Bytecode parsing error: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
Detailed message:
Error: Bytecode parsing error: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
Trace:
	at parsing io.sentry.DefaultSentryClientFactory.createMarshaller(DefaultSentryClientFactory.java:478)
Call path from entry point to io.sentry.DefaultSentryClientFactory.createMarshaller(Dsn):
	at io.sentry.DefaultSentryClientFactory.createMarshaller(DefaultSentryClientFactory.java:461)
	at io.sentry.DefaultSentryClientFactory.createStdOutConnection(DefaultSentryClientFactory.java:449)
	at io.sentry.DefaultSentryClientFactory.createConnection(DefaultSentryClientFactory.java:330)
	at io.sentry.DefaultSentryClientFactory.createSentryClient(DefaultSentryClientFactory.java:236)
	at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:64)
	at io.sentry.Sentry.init(Sentry.java:81)
	at io.sentry.Sentry.init(Sentry.java:44)
	at io.sentry.Sentry.getStoredClient(Sentry.java:102)
	at io.sentry.Sentry.capture(Sentry.java:177)
	at io.sentry.SentryUncaughtExceptionHandler.uncaughtException(SentryUncaughtExceptionHandler.java:55)
	at com.oracle.svm.core.thread.JavaThreads.dispatchUncaughtException(JavaThreads.java:485)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:175)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original exception that caused the problem: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredConstructors(HotSpotResolvedObjectTypeImpl.java:910)
	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:164)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:255)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:170)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:69)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupConstant(WrappedConstantPool.java:144)
	at org.graalvm.compiler.java.BytecodeParser.lookupConstant(BytecodeParser.java:3911)
	at org.graalvm.compiler.java.BytecodeParser.genLoadConstant(BytecodeParser.java:3639)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:4633)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3116)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2925)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:887)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:781)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:196)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:315)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:186)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:500)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more

Error: Image building with exit status 1
```

**Comment by cstancu** [comment]
Thanks for your report. I assume your jar is missing `javax/servlet/http/HttpServletRequest`, however `-H:+ReportUnsupportedElementsAtRuntime` should push the error at run time. I'll look into it.

**Comment by cstancu** [comment]
The issue is fixed in https://github.com/oracle/graal/commit/ae4804b186cc35d39436c1dd9c5869639d436a9c.

**Comment by dariusf** [comment]
Thanks for responding so quickly! The problem still occurs though; seems like [this constructor call](https://github.com/oracle/graal/blob/fb04b787128e94d385e9aea17104642d52d41629/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisUniverse.java#L255) is still reachable.

```
    analysis:  65,980.55 ms
fatal error: java.lang.NoClassDefFoundError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:381)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:281)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:378)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:104)
Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredConstructors(HotSpotResolvedObjectTypeImpl.java:910)
	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:164)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:255)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:170)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:69)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType0(UniverseMetaAccess.java:89)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType(UniverseMetaAccess.java:80)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:45)
	at com.oracle.svm.hosted.ameta.HostedDynamicHubFeature.replace(HostedDynamicHubFeature.java:54)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:521)
	at com.oracle.graal.pointsto.ObjectScanner.scanArray(ObjectScanner.java:195)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:276)
	at com.oracle.graal.pointsto.ObjectScanner.finish(ObjectScanner.java:315)
	at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:81)
	at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:63)
	at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:583)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:554)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:642)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:364)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
```

I've worked around it temporarily by removing the dependency (Sentry) which references `HttpServletRequest`.

**Comment by cstancu** [comment]
I'll close this since it is an old issue that should be fixed in the latest GraalVM RC. Please reopen if you still have problems.
