### ISSUE TITLE
java.lang.ExceptionInInitializerError when trying to create native image for program using XML processing

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#8075]
### Describe the issue
When trying to generate a `native-image` from a Java program that happens to use the XML stack from the JDK (module `java.xml`), then there is a chance that a `ExceptionInInitializerError` happens during the `native-image` build because class loading during the native-image build isn't deterministic. Therefore, in programs in the wild where we have seen the issue, it sometimes happens. Sometimes not. Depending on class loading order and state of inline-before-analysis.

This is hard to reproduce with plain OpenJDK, since the public XML APIs carefully make sure that certain classes are being loaded in the correct order.

The reproducer provided simulates the issue we've observed.

### Steps to reproduce the issue

```
$ cat Test.java
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;

import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Document;

public class Test {

    private static final String CLASS = "com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl";
    
    private void loadFragmentScannerSingle() throws Exception {
        Class<?> fragmentClass = Class.forName(CLASS);
        System.out.println("Loaded: " + fragmentClass);
    }
    
    private void doXmlProcessing(Path xml) throws Exception {
        var dbf = DocumentBuilderFactory.newInstance();
        var db = dbf.newDocumentBuilder();
        Document doc;
        try (var is = Files.newInputStream(xml)) {
            doc = db.parse(is);
        }
        System.out.println("Child nodes: " + doc.getChildNodes().getLength());
        System.out.println("First child: " + doc.getChildNodes().item(0).getNodeName());
        loadFragmentScannerSingle();
    }
    
    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            System.out.println("Usage: Test <1|2 xml-file>");
            System.exit(1);
        }
        int number = Integer.parseInt(args[0]);
        Test t = new Test();
        if (number == 1) {
            t.loadFragmentScannerSingle();
        } else if (number == 2) {
            Path xml = Path.of(args[1]);
            t.doXmlProcessing(xml);
        } else {
            throw new IllegalArgumentException("Illegal value: " + Arrays.asList(args));
        }
    }

}
$ cat test.xml
<point>
    <x>1</x>
    <y>y</y>
</point>
$ javac Test.java
$ native-image Test
========================================================================================================================
GraalVM Native Image: Generating 'test' (executable)...
========================================================================================================================
[1/8] Initializing...                                                                                    (2.7s @ 0.18GB)
 Java version: 23-beta+2-ea, vendor version: Mandrel-24.1.0-dev
 Graal compiler: optimization level: 2, target machine: x86-64-v3
 C compiler: gcc (redhat, x86_64, 13.2.1)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 1 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 26.49GB of memory (42.3% of 62.56GB system memory, determined at start)
 - 12 thread(s) (100.0% of 12 available processor(s), determined at start)
[2/8] Performing analysis...  []                                                                         (1.4s @ 0.22GB)
    1,091 reachable types   (49.1% of    2,220 total)
      667 reachable fields  (21.8% of    3,054 total)
    3,093 reachable methods (33.6% of    9,198 total)
      313 types,    31 fields, and   144 methods registered for reflection

Error: Class initialization of com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl failed. Use the option 

    '--initialize-at-run-time=com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl'

 to explicitly request initialization of this class at run time.
------------------------------------------------------------------------------------------------------------------------
                         0.1s (2.3% of total time) in 8 GCs | Peak RSS: 0.62GB | CPU load: 6.25
========================================================================================================================
Finished generating 'test' in 4.4s.
```

### Expected behaviour:
The native-image build passes. Note that the suggested work-around to use `--initialize-at-run-time` cannot be used as quarkus still uses build time init for various reasons.

### Actual behaviour:
The native-image build (randomly) fails with an `ExceptionInInitializerError` as root cause. For example from the [original quarkus issue](https://github.com/quarkusio/quarkus/issues/37657):
```
Exception java.lang.NullPointerException [in thread "main"]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.getRecognizedProperties(XMLDocumentFragmentScannerImpl.java:764)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.getRecognizedProperties(XMLDocumentScannerImpl.java:449)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.addRecognizedParamsAndSetDefaults(XML11Configuration.java:1518)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.addComponent(XML11Configuration.java:1462)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.<init>(XML11Configuration.java:612)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XIncludeAwareParserConfiguration.<init>(XIncludeAwareParserConfiguration.java:136)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XIncludeAwareParserConfiguration.<init>(XIncludeAwareParserConfiguration.java:93)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.SAXParser.<init>(SAXParser.java:121)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.<init>(SAXParserImpl.java:405)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.<init>(SAXParserImpl.java:137)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.<init>(SAXParserImpl.java:124)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl.newSAXParserImpl(SAXParserFactoryImpl.java:104)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl.setFeature(SAXParserFactoryImpl.java:144)
	at java.xml/javax.xml.catalog.CatalogImpl.getParser(CatalogImpl.java:312)
	at java.xml/javax.xml.catalog.CatalogImpl.parse(CatalogImpl.java:290)
	at java.xml/javax.xml.catalog.CatalogImpl.load(CatalogImpl.java:171)
	at java.xml/javax.xml.catalog.CatalogManager.catalog(CatalogManager.java:73)
	at java.xml/jdk.xml.internal.JdkCatalog.init(JdkCatalog.java:43)
	at java.xml/jdk.xml.internal.XMLSecurityManager.prepareCatalog(XMLSecurityManager.java:305)
	at java.xml/jdk.xml.internal.XMLSecurityManager.<init>(XMLSecurityManager.java:290)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl.<init>(SAXParserFactoryImpl.java:72)
	at java.xml/jdk.xml.internal.JdkXmlUtils.getSAXFactory(JdkXmlUtils.java:441)
	at java.xml/jdk.xml.internal.JdkXmlUtils.<clinit>(JdkXmlUtils.java:97)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.<clinit>(XMLDocumentFragmentScannerImpl.java:193)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupport.ensureClassInitialized(ClassInitializationSupport.java:177)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.AllowAllHostedUsagesClassInitializationSupport.computeInitKindAndMaybeInitializeClass(AllowAllHostedUsagesClassInitializationSupport.java:191)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.AllowAllHostedUsagesClassInitializationSupport.computeInitKindAndMaybeInitializeClass(AllowAllHostedUsagesClassInitializationSupport.java:160)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.AllowAllHostedUsagesClassInitializationSupport.computeInitKindAndMaybeInitializeClass(AllowAllHostedUsagesClassInitializationSupport.java:160)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.AllowAllHostedUsagesClassInitializationSupport.computeInitKindAndMaybeInitializeClass(AllowAllHostedUsagesClassInitializationSupport.java:129)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupport.maybeInitializeAtBuildTime(ClassInitializationSupport.java:161)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupport.maybeInitializeAtBuildTime(ClassInitializationSupport.java:150)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.SVMHost.isInitialized(SVMHost.java:323)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.isInitialized(AnalysisType.java:920)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.maybeEagerlyInitialize(BytecodeParser.java:4488)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4694)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4683)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4678)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5488)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3470)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.iterateBytecodesForBlock(SharedGraphBuilderPhase.java:790)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3430)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3272)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.build(BytecodeParser.java:1136)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.build(SharedGraphBuilderPhase.java:202)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1028)
	at jdk.graal.compiler/jdk.graal.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:102)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:154)
	at jdk.graal.compiler/jdk.graal.compiler.phases.Phase.run(Phase.java:49)
	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:435)
	at jdk.graal.compiler/jdk.graal.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.graal.compiler/jdk.graal.compiler.phases.Phase.apply(Phase.java:38)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:144)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.parseGraph(AnalysisMethod.java:888)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsedHelper(AnalysisMethod.java:853)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:836)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysisGraphDecoder.java:175)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1215)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:1198)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:1053)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.handleInvokeWithCallTarget(PEGraphDecoder.java:1005)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:991)
	at jdk.graal.compiler/jdk.graal.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:930)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysisGraphDecoder.java:343)
	at jdk.graal.compiler/jdk.graal.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:658)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:895)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:73)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:198)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:608)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:167)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:152)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraphInfo(MethodTypeFlow.java:110)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:114)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:628)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:538)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:169)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:154)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool.externalHelpQuiesce(ForkJoinPool.java:2519)
	at java.base/java.util.concurrent.ForkJoinPool.helpQuiescePool(ForkJoinPool.java:2553)
	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3784)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:210)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.doTypeflow(PointsToAnalysis.java:576)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.finish(PointsToAnalysis.java:564)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:153)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:795)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:573)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:538)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:524)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:699)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:139)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
```

### Describe GraalVM and your environment:

GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: https://github.com/oracle/graal/commit/7dd936225350be32f72d52b84f0e59a39cf3c299

JDK major version: 23+2
OS: Fedora 39
Architecture: AMD64

### More details

The actual underlying issue is that after [JDK-8306055](https://bugs.openjdk.org/browse/JDK-8306055), classes such as `com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl` fail the class initializer if loaded in the wrong order. That class depends on `jdk.xml.internal.JdkXmlUtils` to be loaded first.

This can be simulated with the `Test.java` class as follows:

```
$ java Test 1
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.<clinit>(XMLDocumentFragmentScannerImpl.java:193)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:413)
	at java.base/java.lang.Class.forName(Class.java:404)
	at Test.loadFragmentScannerSingle(Test.java:14)
	at Test.main(Test.java:38)
Caused by: java.lang.NullPointerException: Cannot invoke "[Ljava.lang.String;.clone()" because "com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.RECOGNIZED_PROPERTIES" is null
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.getRecognizedProperties(XMLDocumentFragmentScannerImpl.java:764)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.getRecognizedProperties(XMLDocumentScannerImpl.java:449)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.addRecognizedParamsAndSetDefaults(XML11Configuration.java:1518)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.addComponent(XML11Configuration.java:1462)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.<init>(XML11Configuration.java:612)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XIncludeAwareParserConfiguration.<init>(XIncludeAwareParserConfiguration.java:136)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XIncludeAwareParserConfiguration.<init>(XIncludeAwareParserConfiguration.java:93)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.SAXParser.<init>(SAXParser.java:121)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.<init>(SAXParserImpl.java:405)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.<init>(SAXParserImpl.java:137)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.<init>(SAXParserImpl.java:124)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl.newSAXParserImpl(SAXParserFactoryImpl.java:104)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl.setFeature(SAXParserFactoryImpl.java:144)
	at java.xml/javax.xml.catalog.CatalogImpl.getParser(CatalogImpl.java:312)
	at java.xml/javax.xml.catalog.CatalogImpl.parse(CatalogImpl.java:290)
	at java.xml/javax.xml.catalog.CatalogImpl.load(CatalogImpl.java:171)
	at java.xml/javax.xml.catalog.CatalogManager.catalog(CatalogManager.java:73)
	at java.xml/jdk.xml.internal.JdkCatalog.init(JdkCatalog.java:43)
	at java.xml/jdk.xml.internal.XMLSecurityManager.prepareCatalog(XMLSecurityManager.java:305)
	at java.xml/jdk.xml.internal.XMLSecurityManager.<init>(XMLSecurityManager.java:290)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl.<init>(SAXParserFactoryImpl.java:72)
	at java.xml/jdk.xml.internal.JdkXmlUtils.getSAXFactory(JdkXmlUtils.java:441)
	at java.xml/jdk.xml.internal.JdkXmlUtils.<clinit>(JdkXmlUtils.java:97)
	... 6 more
```

However, when `jdk.xml.internal.JdkXmlUtils` is loaded first, loading `com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl` passes as well. This can be simulated with:

```
$ java Test 2 test.xml 
Child nodes: 1
First child: point
Loaded: class com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl
```

We've seen XML (in particular jaxb) using apps fail to generate a native-image randomly in quarkus. The full details are in:
https://github.com/quarkusio/quarkus/issues/37657

**Comment by jerboaa** [comment]
https://github.com/oracle/graal/pull/8076 is a proposed patch. But there might be a better way.

**Comment by jerboaa** [comment]
https://github.com/graalvm/mandrel/issues/644 is a good issue which shows in various comments that sometimes the initializer fails and sometimes passes as it depends on the order of class loading.

**Comment by christianwimmer** [comment]
Please report that also as an OpenJDK bug. Any Native Image fix is just a workaround, and we want to remove the workaround again as soon a the problem is fixed in OpenJDK.

**Comment by jerboaa** [comment]
> Please report that also as an OpenJDK bug. Any Native Image fix is just a workaround, and we want to remove the workaround again as soon a the problem is fixed in OpenJDK.

Will do. I'll report back with a link once done. Thanks!

**Comment by jerboaa** [comment]
JDK bug report is here: https://bugs.openjdk.org/browse/JDK-8323740

**Comment by jerboaa** [comment]
https://github.com/oracle/graal/pull/8193 would be the PR which should fix this once merged.

**Comment by jerboaa** [comment]
> #8193 would be the PR which should fix this once merged.

Closing this issue, since that PR merged. We'll re-open should we see the issue again in our CI.

**Comment by zakkak** [comment]
I believe the reason we are still seeing the issue is because Quarkus registers all classes for build-time initialization by default by invoking `org.graalvm.nativeimage.hosted.RuntimeClassInitialization.initializeAtBuildTime({""})` as a result the classes are still not force-initialized (which to be honest shouldn't solve the issue in the first place since there would be no guarantee regarding the initialization order).

It looks like this was clearly stated in https://github.com/oracle/graal/pull/8193#issue-2087719119 but we missed it:

> The new "allow all hosted usage" class initialization policy behaved differently than the old one: when registering a class (**not a package**) with initializeAtBuildTime

Note also that in Quarkus the issue seems to be triggered by the explicit registration for reflective accesses of some classes under `com.sun.xml.internal.stream`. For more details please refer to https://github.com/quarkusio/quarkus/issues/37657#issuecomment-1858517169

**Comment by jerboaa** [comment]
> (which to be honest shouldn't solve the issue in the first place since there would be no guarantee regarding the initialization order)

That was my thinking as well.

**Comment by zapster** [comment]
Yes, the initialization order is still not defined. However given the fact that only classes are eagerly initialized but not packages, adding `--initialize-at-build-time="jdk.xml.internal.JdkXmlUtils"` explicitly should work, as it would eagerly initialize `JdkXmlUtils`, while the other classes captured by the "initialize all packages at build time" are initialized later. This is of course just a work around.

We might need new API to express class initialization dependencies (which are only needed because of a bug in the JDK code, see https://github.com/oracle/graal/issues/8075#issuecomment-1892431641). But that might need detailed discussion and thus take a while.

**Comment by christianwimmer** [comment]
`--initialize-at-built-time` with a concrete class leads to immediate initialization of that class in the image generator when the options are parsed. It does not matter if there is any other `--initialize-at-build-time` for the package too (or even the wildcard "initialize everything"). The order is also well defined: the classes are initialized in the order that they are listed on the command line, i.e., when you do `--initialize-at-build-time=A,B` then class `A` is initialized before `B`. And it all happens in the same thread because at that time we have not even started the parallel analysis.

**Comment by christianwimmer** [comment]
@jerboaa @zakkak just to be sure, you know that #8076 is not merged yet, i.e., `jdk.xml.internal.JdkXmlUtils` is not yet initialized early?

**Comment by zakkak** [comment]
> @jerboaa @zakkak just to be sure, you know that #8076 is not merged yet, i.e., `jdk.xml.internal.JdkXmlUtils` is not yet initialized early?

Yes, our understanding was that initially https://github.com/oracle/graal/pull/8185 (see https://github.com/oracle/graal/pull/8076#discussion_r1455420589) and later https://github.com/oracle/graal/pull/8193 (which superseded https://github.com/oracle/graal/pull/8185) would suffice and there was nothing extra required (see https://github.com/oracle/graal/pull/8076#issuecomment-1898391252 and https://github.com/quarkusio/quarkus/issues/37657#issuecomment-1895999413) which led to us closing https://github.com/oracle/graal/pull/8076.

My now understanding is that you plan to merge https://github.com/oracle/graal/pull/8256 which supersedes https://github.com/oracle/graal/pull/8076 and this will resolved the issue without the need to do anything more on the Quarkus side. Is that correct?

**Comment by christianwimmer** [comment]
Fixed in the master branch in #8256, and fixed in the 24.0 release branch in https://github.com/oracle/graal/commit/df761b6bb7178647ed29bacddf6e54ef183fded0
