### ISSUE TITLE
[GR-51322] Cpuid1Ecx feature parsing is incorrect for AMD CPUs

### ISSUE THREAD

**Issue by MatiasT** [oracle/graal#8143]
**Describe the issue**
While running a GraalVM-compiled [quarkus](https://github.com/parasjain27031994/quarkus-quick-start) binary within a [Firecracker MicroVM](https://github.com/firecracker-microvm/firecracker) masking off some specific cpu features on an AMD-Milan instance we received the following error message particularly related to `LZCNT` not being properly parsed.

```
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
```

Upon research we found a bug report for OpenJDK perfectly matching what we observed https://bugs.openjdk.org/browse/JDK-8280867

We verified that the same bug is happening with the GraalVM binary by both debugging with GDB and confirming GraalVM was trying to read `LZCNT` in the bit 6 instead of 5, and by setting the `SSE4A` bit (bit 6) in the MicroVM, which solved the issue.

This issue is also resolved if compiled using `-march=x86-64-v2`, which does not require `LZCNT`

As mentioned in the JDK issue, this has gone unnoticed because modern CPUs usually have all the involved bits set, so the impact is not visible unless you explicitly decide to mask off some of them.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Set up an AMD Milan instance (e.g Amazon's EC2 m6a.metal) 
2. Follow the Firecracker get-started doc to set up a MicroVM using the T2A template
3. Clone https://github.com/parasjain27031994/quarkus-quick-start
4. run `./mvnw install -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.0-jdk-17` to generate an executable binary
5. copy it into the created MicroVM
6. Run said binary to see the failure

**Describe GraalVM and your environment:**
 - GraalVM version: latest version in quarkus' container builder
 
```
native-image 21.0.1 2023-10-17
GraalVM Runtime Environment GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
Substrate VM GraalVM CE 21.0.1+12.1 (build 21.0.1+12, serial gc)
```
 - JDK major version: **21**
 - OS: **Amazon Linux 2**
 - Architecture: **AMD64**

**More details**
The bug is partially present in this struct https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.native.libchelper/include/amd64hotspotcpuinfo.h#L138-L151

Which seem to have been copied before the bug was identified and fixed.

This commit fixed the problem for OpenJDK: https://github.com/openjdk/jdk/commit/a18beb4797a1ca6fc6b31e997be48b2bd91c6ac0

**Comment by fniephaus** [comment]
Thanks for raising this and the in-depth analysis! I'll make sure this is fixed in GraalVM asap.

**Comment by fniephaus** [comment]
I have opened #8159 that ports the JDK fix to Native Image.

**Comment by upivcom** [comment]
I have the same problem, we migrated to native quarkus 3.6.5 and java 21.0.2 zulu and we have the error below in production, it only occurs a few times, we are running the lambdas on AWS Amazon Linux 2023, sometimes we go back to Amazon Linux 2 version but the problem persists, the solution reported above did not work, does anyone know of a possible solution?

The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].

**Comment by woess** [comment]
> it only occurs a few times
@upivcom are you saying the same native image sometimes prints the error, sometimes works (on a machine that supports these features)? Are you using `-march` (and if so which)?

**Comment by upivcom** [comment]
this, the same image sometimes works and sometimes the error occurs, this in AWS using Amazon Linux 2023, below the compilation settings

![image](https://github.com/oracle/graal/assets/22225201/bc4fd5d5-8732-4290-ad6a-9f8d2ba95aba)

**Comment by fniephaus** [comment]
The fix from https://github.com/oracle/graal/pull/8159 was [backported to the 23.1 release branch](https://github.com/oracle/graal/commit/5d15e9ea7671ac6476d4a07db5738a0cbba6eeef) and it will ship with [the next CPU release of Oracle GraalVM for JDK 21.0.3 due on April 16, 2024](https://docs.oracle.com/en/graalvm/release-calendar.html). In the meantime, you should be able to work around this problem by using `-march=x86-64-v2`.

Hope this helps!

**Comment by AnandRa007** [comment]
Hello @fniephaus , is this https://github.com/oracle/graal/issues/8143 / https://github.com/oracle/graal/pull/8159 fixed in any of the versions that has been [released](https://docs.oracle.com/en/graalvm/release-calendar.html) recently ?

**Comment by fniephaus** [comment]
Hi @AnandRa007, the fix was backported to the 23.1 release branch (see https://github.com/oracle/graal/commit/5d15e9ea7671ac6476d4a07db5738a0cbba6eeef) and should be included in Oracle GraalVM for JDK 17.0.11 and JDK 21.0.3. I don't know what Mandrel 23.1.3.0 is based on, maybe not on the [23.1.3 release tag](https://github.com/oracle/graal/tree/vm-23.1.3). @zakkak would know.

**Comment by parasjain27031994** [comment]
Hi @fniephaus , has 21.0.3  been released. I could not find this version in release page ?
https://www.graalvm.org/release-notes/JDK_21/

**Comment by zakkak** [comment]
> As per @zakkak 's comment in https://github.com/graalvm/mandrel/issues/660#issuecomment-2069235257 the issue has not been fixed in 23.1.3.0.

It seems like there was a misunderstanding here. In my comment I meant that the release date is not fixed yet, not the issue. Sorry for the ambiguity.

**Comment by upivcom** [comment]
good afternoon,
Here we are using the 21.0.3 Zulu version of Java, native compilation for Quarkus, we had added this option: -Dquarkus.native.builder-image=graalvm

However, the problem reoccurred in the AWS CloudWatch logs:
![image](https://github.com/oracle/graal/assets/22225201/a2f85e73-936a-4a0c-94ab-a582e79161ea)

**Comment by zakkak** [comment]
@upivcom why are you using `-Dquarkus.native.builder-image=graalvm`? The GraalVM CE based Quarkus builder images do not include the backport. The issue should be fixed in the mandrel image though. Can you try without that parameter?

**Comment by upivcom** [comment]
Without this parameter the problem persists in version 21.0.3 Zulu, DevOps added this parameter and reduced the occurrences that still follow, as below, there is no version 21.0.3 for the GraalVM CE version, we also did not test with the GraalVM Oracle version, the The problem persists and is not simple to resolve.

Doing some research, I identified that the problem started with version 3.2.0 of the quarkus plugin and we are using version 3.6.5, if I change to version 3.1.3.Final will the problem not be fixed?

using sdkman which correct version of java could definitively solve the problem, as I said GraalVM CE does not exist in version 21.0.3

  GraalVM CE |      | 22 | graalce |             | 22-graalce          
                |      | 22.0.1 | graalce |             | 22.0.1-graalce      
                |      | 21.0.2 | graalce |             | 21.0.2-graalce      
                |      | 21.0.1 | graalce |             | 21.0.1-graalce      
                |      | 17.0.9 | graalce |             | 17.0.9-graalce      
  GraalVM Oracle|      | 23.ea.9 | grail |             | 23.ea.9-grail       
                |      | 23.ea.8 | grail |             | 23.ea.8-grail       
                |      | 23.ea.7 | grail |             | 23.ea.7-grail       
                |      | 23.ea.6 | grail |             | 23.ea.6-grail       
                |      | 23.ea.5 | grail |             | 23.ea.5-grail       
                |      | 23.ea.3 | grail |             | 23.ea.3-graal       
                |      | 22 | grail |             | 22-grail            
                |      | 22.0.1 | grail |             | 22.0.1-grail        
                |      | 21.0.3 | grail |             | 21.0.3-grace

**Comment by zakkak** [comment]
> Without this parameter the problem persists in version 21.0.3 Zulu,

Hi @upivcom, the Zulu JVM is irrelevant to native-image compilation. 

> Doing some research, I identified that the problem started with version 3.2.0 of the quarkus plugin and we are using version 3.6.5, if I change to version 3.1.3.Final will the problem not be fixed?

It will probably be "fixed" because in Quarkus 3.2 we moved to Mandrel 23.0.x while Quarkus 3.1 was using Mandrel 22.3.x. Note however that it's not advised to switch to 3.1.3.Final as it's no longer supported. Your best option would be to upgrade to 3.8 which will be supported till February 2025 (Quarkus 3.2 will be supported till July 2024)  or the latest Quarkus version if you are willing to keep updating on a regular bases. 

> using sdkman which correct version of java could definitively solve the problem, as I said GraalVM CE does not exist in version 21.0.3

So using `21.0.3-graal` from sdkman resolves the issue, right? Did you try `23.1.3.1.r21-mandrel` (again from sdkman) as well?

Could you please post the `Java version` printed by the builder image when not using `-Dquarkus.native.builder-image=graalvm` in your pipelines? (like you did in https://github.com/oracle/graal/issues/8143#issuecomment-2045161354) Please use a recent run.

**Comment by fniephaus** [comment]
> Hi @fniephaus , has 21.0.3 been released. I could not find this version in release page ?
https://www.graalvm.org/release-notes/JDK_21/

@parasjain27031994 We are working on fixing this, thanks for the ping! In the meantime, you need to take a look at this page instead: https://docs.oracle.com/en/graalvm/jdk/21/docs/release-notes/

**Comment by upivcom** [comment]
Good evening, just to inform you, I placed the property below in the application.properties file and today no error occurred in production running Java 21.0.3 Zulu and Quarkus 3.6.5, we kept this property Dquarkus.native.builder-image=graalvm

quarkus.native.additional-build-args=-march=compatibility
